### ISSUE TITLE
Wine Quality Dataset 

### ISSUE THREAD

**Issue by varunkhanna1993** [abhishekkrthakur/approachingalmost#10]
There is an issue with the code when I run the .fit on the first decision tree.

ValueError: Number of labels=599 does not match number of samples=1000

Do you have any idea what is causing this issue?

**Comment by rashmibanthia** [comment]
If you change `clf.fit(df_train[cols], df_test.quality)` to `clf.fit(df_train[cols], df_train.quality)`  (on Page 17) it should work. It's happening because number of samples are not same in df_train and df_test.

**Comment by abhishekkrthakur** [comment]
sorry for the typo :)

**Comment by epogrebnyak** [comment]
We need some labelling for the issues - this is clealy useful to mark aas `Typo` and close after new edition or revision is out. 

@abhishekkrthakur - maybe you can grant some priviliges on this repo, so we can help sort out the issues?
