### ISSUE TITLE
sturge rule number of bin creation type error

### ISSUE THREAD

**Issue by anandsm7** [abhishekkrthakur/approachingalmost#11]
Ubuntu : 16.4
I have encountered an error while creating stratified kfolds for regression problem
```
def create_folds(data):
    data["kfold"] = -1
    data = data.sample(frac=1).reset_index(drop=True)
    
    #calculate number of bins by sturge's rule
    num_bins = np.floor(1 + np.log2(len(data)))
    
    #bins targets
    data.loc[:, "bins"] = pd.cut(data["target"],
                                 bins = num_bins,
                                 labels=False
                                ) 
```
num of bin type must be changed from float to int
`num_bins = np.floor(1 + np.log2(len(data))).astype(np.int32)`

Hope it helps

**Comment by abhishekkrthakur** [comment]
yes. I believe it worked in the version of pandas I used at the time of writing the book.
Thanks for creating the issue. I will keep it open as a reference to others :)
