### ISSUE TITLE
Fig 10 : Formula for R2

### ISSUE THREAD

**Issue by Geethi2020** [abhishekkrthakur/approachingalmost#18]
Hi,
Looks like the squaring is missing in the denominator of the formula for R2 (figure 10, Page 69 in Kindle edition). The code for R2 has squaring in the numerator and denominator and is working as expected.
Thank you,

**Comment by chammami** [comment]
Hi,

I have just came across this typo and double checked it. You are right.

![fig10-typo](https://user-images.githubusercontent.com/40431648/95662237-c61e9f80-0b35-11eb-81b6-a12414c41557.png)

Hope it helps,
Great book so far :)

**Comment by abhishekkrthakur** [comment]
It seems like a typo. Code should be fine :)
