### ISSUE TITLE
environment.yml does not work in OSX

### ISSUE THREAD

**Issue by dsanyal** [abhishekkrthakur/approachingalmost#2]
Hi Abhishek,
Your environment.yml file is platform-specific (for Linux) and a strict export, which means that I can't use this file to recreate the conda environment in OSX. Is there an easy fix to this? Maybe you should run `conda env export --from-history -f environment.yml` just to get the package and version information and upload it?

Thanks.

**Comment by vochicong** [comment]
Hi @abhishekkrthakur , 

Thank you for adding the `environment_osx.yml` file to the repository, but running
`conda env create -f environment_osx.yml` gets an error.

```
Pip subprocess error:
  ERROR: Could not find a version that satisfies the requirement python-graphviz==0.13 (from -r /Users/congvc/approachingalmost/condaenv._voz6otr.requirements.txt (line 77)) (from versions: none)
ERROR: No matching distribution found for python-graphviz==0.13 (from -r /Users/congvc/approachingalmost/condaenv._voz6otr.requirements.txt (line 77))
```

BTW, can you share how to create these `environment*.yml` files?

**Comment by abhishekkrthakur** [comment]
Can you please try the new env file I just pushed?

I use : `conda env export | grep -v "^prefix: " > environment.yml`

**Comment by vochicong** [comment]
I've tried the new env file, it works! Thank you.

**Comment by abhishekkrthakur** [comment]
Great!
