### ISSUE TITLE
Datasets missing here

### ISSUE THREAD

**Issue by paulocr2** [abhishekkrthakur/approachingalmost#25]
Datasets such as winequality-red.csv, use in the cross-validation section, is not available here. No datasets are available here at all.

I am aware that the datasets could be found elsewhere, but this place should be self-contained. 

You have put references to the references. But why not place the datasets here? It ensures consistency as the references may change. Every other book I have seen have the datasets used in the repo, except when these data sets are available in a package.

**Comment by abhishekkrthakur** [comment]
https://www.kaggle.com/abhishek/aaamlp 

If something is missing, please let me know.

**Comment by abhishekkrthakur** [comment]
does it solve your issue @paulocr2 ?

**Comment by abhishekkrthakur** [comment]
considering it to be solved now.
