### ISSUE TITLE
error in the code of "winequality-red"

### ISSUE THREAD

**Issue by PipePiper** [abhishekkrthakur/approachingalmost#27]
![image](https://user-images.githubusercontent.com/63913227/100552181-aabb4f80-32af-11eb-9ee1-9c89c258f91f.png)
Throws the following error: Number of labels=599 does not match number of samples=1000

**Comment by abhishekkrthakur** [comment]
The error is a typo that can be fixed by reading the line of code itself. Also, where did you download the book from?

**Comment by PipePiper** [comment]
Okay, thanks. I got the book from Library Genesis.

**Comment by abhishekkrthakur** [comment]
Great. i dont like to respond to questions from people who downloaded the book from unofficial sources. This typo is fixed in official versions. Please check them before asking.
