### ISSUE TITLE
environment.yml has some package versions issues 

### ISSUE THREAD

**Issue by amrutheshreddy** [abhishekkrthakur/approachingalmost#3]
Hi,
 environment.yml has package issues and pip subprocess fail error is generated due to few packages in ubuntu with miniconda installed

**Comment by abhishekkrthakur** [comment]
Could you please paste the error?

**Comment by amrutheshreddy** [comment]
Hi Abhishek,

Pls, find here attached with the screenshots. Though the packages with the version issues are removed in the environment file and then tried creating environment. The issue persists.

Regards,
amruthesh

[Image.jpeg]
Get Outlook for iOS[Image.jpeg]<https://aka.ms/o0ukef>
________________________________

**Comment by abhishekkrthakur** [comment]
screenshot did not attach?

**Comment by amrutheshreddy** [comment]
Hi,

Pls find the trailing email with the required screenshots.

Regards,
Amruthesh

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dipta007** [comment]
I am facing this issue @abhishekkrthakur , Thanks for the help

![image](https://user-images.githubusercontent.com/13894030/87965742-114c8780-cade-11ea-9f2b-d3488951f931.png)

**Comment by HarshitShukla25** [comment]
For me it broke somewhere in the middle of downloading the packages.Guess some of them have just deprecated their previous versions.for eg. You can't do pip install tensorflow=2.1.1. .

**Comment by abhishekkrthakur** [comment]
Sorry for the delay. Looking and fixing this today

**Comment by amrutheshreddy** [comment]
Thank you.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by dipta007** [comment]
Hello @abhishekkrthakur is there any update here?
I know you are busy. But looking forward on it.
Thank you

**Comment by abhishekkrthakur** [comment]
sorry for the delay.
the issue has been fixed. 
Please see the bottom of the README :)
