### ISSUE TITLE
New column assignment in pandas

### ISSUE THREAD

**Issue by epogrebnyak** [abhishekkrthakur/approachingalmost#5]
There must be a reason why you prefer `df.loc[:, 'weekofyear'] = ...` to shorter `df['weekofyear'] = ...`, can you please give some hints?

**Comment by akanz1** [comment]
I can think of a few reasons:

"Explicit is better than implicit." (PEP20)

Also it is good practice to use .loc to avoid SettingWithCopy warnings. For the case you've mentioned it shouldn't make any difference but once you start selecting rows I can be ambiguous and it is not guaranteed that you are modifying the original df.

**Comment by epogrebnyak** [comment]
My impression repeated `.loc[]` on the left side of assignment just adds up to boilerplate. 

It would have made mode sense if sometimes we were assigning to slice and sometimes to whole columnn - the explicitness would have counted then greatly (and loc would not be avoided):  

```
df.loc[ix, "a"] = ...
df.loc[~ix, "a"] = ...
```

Also pandas own tutorial creates new columsn without loc: https://pandas.pydata.org/docs/getting_started/intro_tutorials/05_add_columns.html 

Plus: https://stackoverflow.com/questions/12555323/adding-new-column-to-existing-dataframe-in-python-pandas (with considerations for `SettingWithCopyWarning`)

My guess is that `.loc[]` assignment is kind of a drill for further examples in the book (ones with slices and `SettingWithCopyWarning` risk as @kanz1 points out), possibly it is more effiecient too.

**Comment by abhishekkrthakur** [comment]
@epogrebnyak your guess is correct :)

**Comment by epogrebnyak** [comment]
Now when the author has spoken I guess we can close the issue and resort to reading the book ;-)
