### ISSUE TITLE
Visualizing samples in MNIST dataset

### ISSUE THREAD

**Issue by leodoc63** [abhishekkrthakur/approachingalmost#50]
In page 11

single_image = pixel_values[1, :].reshape(28, 28)
plt.imshow(single_image, cmap='gray')

but reshape is not an pd.DataFrame atribute, so to see the image I had to code:

single_image = pixel_values.iloc[1, :]
single_image = single_image.values.reshape(28,28)
plt.imshow(single_image, cmap='gray')

**Comment by weibinqiu** [comment]
thank u  so much
