### ISSUE TITLE
Minor issue on doc string

### ISSUE THREAD

**Issue by pulkitmehtawork** [abhishekkrthakur/approachingalmost#6]
Hi Abhishek , 
There is minor typo in document string .
In chapter ensembling and stacking , function max_voting has document string which says that it creates max predictions . It should be corrected to max voted predictions.

Also , please correct param in doc string . It says param probas . It should be corrected to preds.

**Comment by abhishekkrthakur** [comment]
Thank you for reporting this :)
It is indeed a known issue but shouldn't affect the behaviour of the function

**Comment by pulkitmehtawork** [comment]
yes ,agreed  . once again thanks for writing a great and very useful book .
