### ISSUE TITLE
numpy version is conflicting 

### ISSUE THREAD

**Issue by javedhassans** [abhishekkrthakur/approachingalmost#65]
![image](https://user-images.githubusercontent.com/50239488/156219012-91dcb8fb-0ac9-4ee0-9868-26b0cee8d4c8.png)
The numpy versions are conflicting, instead of having a strict version for numpy, I modified numpy>=1.11 and it installing the requirements.

**Comment by joseruga** [comment]
Did that work for you?

**Comment by srsaito** [comment]
@javedhassans's suggestion got the pip install to work for me. But I haven't started the course yet, so we'll see if there are later problems from that change.

**Comment by smashpumpkin** [comment]
change the numpy version to 1.18.0 will be ok in my case
