### ISSUE TITLE
Error occurred while running 'conda env create -f environment.yml'

### ISSUE THREAD

**Issue by THEMrinaal** [abhishekkrthakur/approachingalmost#7]
![error](https://user-images.githubusercontent.com/29385581/88466690-c76bf480-ce83-11ea-8c6c-21f310215428.png)

**Comment by ramchandracheke** [comment]
I am also getting same error . Ihave installed in on Ubuntu 20.04.

**Comment by ramchandracheke** [comment]
If you face problems with the environment files, please try the following instead

delete the ml enviornment that was created earlier: conda env remove --name ml

create a new environment: conda create -n ml python=3.7.6

activate the environment: conda activate ml

install python packages: pip install -r requirements.txt

**Comment by abhishekkrthakur** [comment]
Please see readme
