### ISSUE TITLE
Arranging machine learning projects as GH template

### ISSUE THREAD

**Issue by callmephilip** [abhishekkrthakur/approachingalmost#79]
Has anyone converted project setup suggested in "Arranging machine learning projects" into a public GH template? Is it something that the author would be/is OK with?

**Comment by abhishekkrthakur** [comment]
feel free :)

**Comment by callmephilip** [comment]
i set up initial version of this here -> https://github.com/bakery/aaamlp-starter. I am updating this as I am making my way through your excellent book. thank you
